apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jhipster4-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jhipster4-demo
    spec:
      containers:
        - name: jhipster4-demo
          image: "jhipster4-demo:latest"
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 10
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest                   
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=cicd-k8s:us-central1:blog=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
          - name: cloudsql-oauth-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
          - name: cloudsql
            mountPath: /cloudsql
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: cloudsql
          emptyDir:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs